In [1]:
import pandas as pd

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله اول
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در ابتدا، دو مجموعه‌داده را از پوشهٔ داده بارگذاری کنید.

<br>
Data/athlete_events.csv
</font>
</p>

In [2]:
df=pd.read_csv("athlete_events.csv")
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله دوم
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این مرحلهٔ اختیاری، با استفاده از توابع info() و describe() در کتابخانهٔ Pandas، می‌توانید ساختار کلی و آمار توصیفی مجموعه‌داده را بررسی کرده و درک بهتری از ویژگی‌های آن به‌دست آورید.
</font>
</p>

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [4]:
df.describe()

,ID,Age,Height,Weight,Year
count,271116.000000,261642.000000,210945.000000,208241.000000,271116.000000
mean,68248.954396,25.556898,175.338970,70.702393,1978.378480
std,39022.286345,6.393561,10.518462,14.348020,29.877632
min,1.000000,10.000000,127.000000,25.000000,1896.000000
25%,34643.000000,21.000000,168.000000,60.000000,1960.000000
50%,68205.000000,24.000000,175.000000,70.000000,1988.000000
75%,102097.250000,28.000000,183.000000,79.000000,2002.000000
max,135571.000000,97.000000,226.000000,214.000000,2016.000000

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله سوم
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
تعداد مقادیر گمشده (NaN) در هر ستون از مجموعه‌داده را محاسبه کنید. این تحلیل به شناسایی ستون‌هایی که دارای داده‌های ناقص هستند کمک می‌کند و امکان تصمیم‌گیری مناسب برای پاک‌سازی یا تکمیل داده‌ها را فراهم می‌سازد.

</font>
</p>

In [5]:
missing_values = df.isna().sum()
missing_values

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
dtype: int64

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله چهارم
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این مرحله، ستون‌هایی را که بیش از نیمی از مقادیرشان گمشده (NaN) هستند، از مجموعه‌داده حذف کنید.

</font>
</p>

In [6]:
df=df.drop(columns=['Medal'])

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله پنجم
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
در این مرحله، باید سطرهای تکراری را از مجموعه‌داده حذف کنید تا تحلیل‌های شما دقیق‌تر و معتبرتر باشد.
</font>
</p>

In [7]:
df = df.drop_duplicates()

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله ششم
</font>
</h3>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
در این بخش، تمام سطرهای مجموعه‌داده که شامل مقادیر NaN (داده‌های خالی یا تعریف نشده) هستند را حذف خواهیم کرد. دقت کنید که پس از این مرحله مجموعه‌داده نباید شامل هیچ مقدار NAN باشد.
</font>
</p>

In [8]:
df=df.dropna()

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله هفتم
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این مرحله، با استفاده از مجموعه داده موجود، می‌خواهیم تعداد ورزشکاران شرکت‌کننده در هر رشته المپیک را محاسبه کنیم. نتیجه این تحلیل را در یک مجموعه داده جدید با ساختار زیر ذخیره خواهیم کرد:

ستون sport: نام رشته ورزشی
<br>
ستون athlete_count: تعداد ورزشکاران شرکت‌کننده در آن رشته

</font>
</p>

In [56]:
sports_count=df.Sport.value_counts()
sports_count = df['Sport'].value_counts()
df1 = sports_count.reset_index()
df1.columns = ['sport', 'athlete_count']
df1

                        sport  athlete_count
0                   Athletics          32374
1                    Swimming          18776
2                  Gymnastics          18271
3                      Rowing           7790
4                     Cycling           7773
5        Cross Country Skiing           7529
6                    Shooting           7260
7                     Fencing           6537
8               Alpine Skiing           6322
9                    Canoeing           5550
10                  Wrestling           5186
11                    Sailing           4863
12                   Biathlon           4615
13                 Ice Hockey           4579
14              Equestrianism           4553
15                   Football           4443
16              Speed Skating           4400
17                     Boxing           4363
18                     Hockey           4264
19                 Basketball           3668
20                       Judo           3366
21                   Handball           3319
22                 Volleyball           3277
23              Weightlifting           2974
24                 Water Polo           2719
25                  Bobsleigh           2205
26                     Diving           2011
27                     Tennis           2008
28                Ski Jumping           1966
29                    Archery           1883
30               Table Tennis           1789
31             Figure Skating           1512
32  Short Track Speed Skating           1488
33                       Luge           1377
34                  Badminton           1362
35          Modern Pentathlon           1259
36            Nordic Combined           1065
37               Snowboarding            924
38           Freestyle Skiing            913
39      Synchronized Swimming            849
40                   Baseball            846
41        Rhythmic Gymnastics            615
42                  Taekwondo            596
43           Beach Volleyball            538
44                  Triathlon            526
45                   Softball            441
46                    Curling            410
47               Rugby Sevens            297
48                   Skeleton            174
49               Trampolining            149
50                       Golf            108
51                      Rugby             30
52                 Tug-Of-War             20
53           Art Competitions             16
54                   Lacrosse              2
55               Motorboating              1

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله هشتم
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
پس از ایجاد مجموعه‌داده در مرحله قبل، اکنون زمان ذخیره‌سازی آن فرا رسیده است. قبل از ذخیره‌سازی، مجموعه‌داده را بر اساس ستون athlete_count به صورت نزولی (از بزرگ‌ترین به کوچک‌ترین مقدار) مرتب کنید.
<br>
سپس، مجموعه‌داده نهایی را در قالب CSV و با نام زیر در همان پوشه‌ای که نوت‌بوک قرار دارد ذخیره نمایید:
<br>
event_counts.csv
<br>

توجه کنید که مجموعه‌داده تنها باید حاوی دو ستونی باشد که در مراحل قبل معرفی کردیم و نباید هیچ شاخصی برای این مجموعه‌داده مشخص کرد.

</font>
</p>

In [57]:
df1.to_csv('event_counts.csv',index=False)

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله نهم
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این بخش مجموعه‌داده جدیدی قرار است که بسازیم. در این بخش، شاخص‌های مهم فیزیولوژیکی ورزشکاران را به تفکیک رشته‌های ورزشی تحلیل می‌کنیم. 
<br>
در این بخش به ازای هر ورزش اطلاعات زیر باید محاسبه گردد:

+ میانگین‌ سن ورزشکاران هر‌رشته (Average_Age)
+ میانگین‌ قد ورزشکاران هر‌رشته (Average_Height)
+ میانگین‌ وزن ورزشکاران هر‌رشته (Average_Weight)
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
مجموعه‌داده جدید باید شامل 4 ستون با نام های زیر باشد:

+ Sport
+ Average_Age
+ Average_Height
+ Average_Weight
</font>
</p>

In [20]:
Average_Age=df.Age.mean()
Average_Height=df.Height.mean()
Average_Weight=df.Weight.mean()

25.054736576587064

In [35]:
df2 = df.groupby('Sport')[['Age', 'Height', 'Weight']].mean().reset_index()
df2.columns=['Sport','Average_Age','Average_Height','Average_Weight']
df2

                        Sport  Average_Age  Average_Height  Average_Weight
0               Alpine Skiing    23.338184      173.516925       72.082648
1                     Archery    26.272969      173.249602       70.014870
2            Art Competitions    41.375000      173.062500       78.250000
3                   Athletics    25.330203      176.276456       69.273738
4                   Badminton    25.800294      174.220264       68.171439
5                    Baseball    26.309693      182.599291       85.718085
6                  Basketball    25.453926      191.226554       85.801799
7            Beach Volleyball    29.135688      186.202602       79.089219
8                    Biathlon    26.657855      174.052004       66.631419
9                   Bobsleigh    28.650794      181.608617       89.161678
10                     Boxing    23.286729      172.867522       65.314233
11                   Canoeing    25.410991      178.552072       76.492072
12       Cross Country Skiing    26.088724      173.263780       65.880462
13                    Curling    31.136585      174.168293       72.131707
14                    Cycling    25.104464      176.192976       70.110897
15                     Diving    22.252113      166.661860       60.569617
16              Equestrianism    34.117944      174.397101       67.803975
17                    Fencing    26.913722      177.295548       71.388481
18             Figure Skating    22.214947      168.148810       59.543651
19                   Football    23.578663      175.436417       70.476142
20           Freestyle Skiing    24.419496      170.940854       67.026835
21                       Golf    29.583333      174.046296       71.194444
22                 Gymnastics    21.688359      162.859668       56.885118
23                   Handball    26.492618      183.483579       81.503465
24                     Hockey    25.647514      173.387899       69.164869
25                 Ice Hockey    25.844944      178.923127       80.837737
26                       Judo    25.410279      174.164884       78.820113
27                   Lacrosse    28.000000      174.000000       66.500000
28                       Luge    24.686275      176.655047       77.282498
29          Modern Pentathlon    26.119142      178.082605       70.281573
30               Motorboating    27.000000      181.000000       77.000000
31            Nordic Combined    24.077934      176.535211       66.915962
32        Rhythmic Gymnastics    18.808130      167.795122       48.760976
33                     Rowing    25.413607      184.265982       80.168870
34                      Rugby    24.100000      173.666667       77.533333
35               Rugby Sevens    26.080808      175.363636       79.006734
36                    Sailing    29.413531      178.270409       75.980465
37                   Shooting    32.011295      173.541598       74.036846
38  Short Track Speed Skating    22.836022      170.108199       64.310484
39                   Skeleton    29.028736      176.224138       74.166667
40                Ski Jumping    23.216684      176.498474       65.087233
41               Snowboarding    24.872294      173.043290       69.527056
42                   Softball    26.229025      169.428571       67.471655
43              Speed Skating    24.215455      174.092500       70.030114
44                   Swimming    20.622870      178.602844       70.597784
45      Synchronized Swimming    22.485277      168.489988       55.856302
46               Table Tennis    26.623812      171.253773       64.915036
47                  Taekwondo    24.083893      176.750000       68.088087
48                     Tennis    25.099602      178.915837       70.802291
49               Trampolining    25.167785      166.563758       59.322148
50                  Triathlon    27.893536      173.640684       61.817490
51                 Tug-Of-War    26.500000      182.550000       91.800000
52                 Volleyball    25.237107      186.978944       78.900214
53                 Water Polo    25.705774      185.036043       84.568224
54              Weightlifting    25.288837      167.805313       79.612811
55                  Wrestling    25.681064      172.418434       75.602777

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله دهم
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
حال در این مرحله قصد داریم تا مجموعه‌داده مرحله قبل را ذخیره کنیم.
<br>

ابتدا مجموعه‌داده را بر اساس ستون Sport به صورت صعودی مرتب کنید.
<br>
سپس مجموعه داده را با نام زیر ذخیره کنید:
<br>
average_stats_by_sport.csv
<br>
توجه کنید که این مجموعه‌داده نباید هیچ ستونی شاخصی داشته باشد و پس از ذخیره شدن باید فقط شامل 4 ستونی باشد که در مرحله قبل معرفی شدند.
</font>
</p>

In [58]:
df2=df2.sort_values(by="Sport",ascending=True)
df2.to_csv('average_stats_by_sport.csv',index=False)

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله یازدهم
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
حال قصد داریم بفهمیم که توزیع جنسیت ورزشکاران در رشته‌های ورزشی مختلف چگونه است.
<br>
مجموعه‌داده جدیدی درست کنید که شامل سه ستون زیر باشد:

+ ستون Sport: نام ورزش
+ ستون Sex: ستونی که جنسیت ورزشکاران یک رشته خاص را مشخص کند.
+ ستون  Count: تعداد ورزشکاران زن یا مرد آن رشته و جنسیت.

</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
این مجموعه‌داده را بر اساس دو ستون Sport و Sex به شکل صعودی مرتب کنید.
<br>
سپس مجموعه‌داده نهایی را که مرتب کرده اید را با نام زیر ذخیره کنید.
<br>
gender_distribution.csv
<br>
در این مرحله، مجموعه‌داده نهایی را با رعایت 2 شرط اساسی ذخیره خواهیم کرد: عدم استفاده از هیچ ستونی به عنوان شاخص ، حفظ صرفاً سه ستون تعیین‌شده (بدون هیچ ستون اضافی). این رویکرد تضمین می‌کند که خروجی نهایی دقیقاً مطابق با الزامات تحلیل بوده و از یکپارچگی داده‌ها اطمینان حاصل می‌شود.
</font>
</p>

In [59]:
df3 = df.groupby(['Sport', 'Sex']).size().reset_index(name='Count')
df3.sort_values(by=['Sport', 'Sex'], ascending=[True, True])
df3.to_csv('gender_distribution.csv',index=False)

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله دوازدهم
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
حال در این مرحله قصد داریم تا مجموعه‌داده جدیدی تولید کنیم. هدف این است که بدانیم کدام کشورها (کمیته‌های ملی المپیک) بیشترین شرکت‌کننده را در المپیک دارند.
<br>

این مجموعه‌داده جدید شامل دو ستون خواهد بود:

+ ستون NOC: نام کشور(کمیته المپیک)
+ ستون participants_by_country: تعداد شرکت‌کنندگان آن کشور 
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
سپس این مجموعه‌داده را بر اساس ستون participants_by_country به ترتیب نزولی  مرتب کنید.
<br>
اگر دارای مقادیر برابر برای ستون participants_by_country بودید، آن را بر اساس ستون NOC به شکل نزولی مرتب کنید.
<br>
در انتها این مجموعه‌داده را با نام زیر در کنار نوت بوک ذخیره کنید:
<br>
participants_by_country.csv
<br>
در این مرحله، مجموعه‌داده نهایی را با رعایت 2 شرط اساسی ذخیره خواهیم کرد: عدم استفاده از هیچ ستونی به عنوان شاخص ، حفظ صرفاً دو ستون تعیین‌شده (بدون هیچ ستون اضافی). این رویکرد تضمین می‌کند که خروجی نهایی دقیقاً مطابق با الزامات تحلیل بوده و از یکپارچگی داده‌ها اطمینان حاصل می‌شود.
</font>
</p>

In [71]:
participants_by_country=df.NOC.value_counts()
df4 = participants_by_country.reset_index()
df4.columns = ['NOC', 'participants_by_country']
df4=df4.sort_values(by=['participants_by_country', 'NOC'], ascending=[False, False])
df4.to_csv('participants_by_country.csv',index=False)

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله سیزدهم
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این مرحله قصد داریم تا بدانیم که تعداد ورزشکاران حاضر در هر دوره از المپیک چقدر بوده است. در ادامه مجموعه‌داده جدیدی ایجاد خواهیم کرد .
<br>
این مجموعه‌داده شامل دو ستون می باشد:

+ ستون Year
+ ستون Number_of_Athletes
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
سپس مجموعه‌داده را بر اساس ستون Number_of_Athletes به شکل نزولی مرتب کنید.
اگر Number_of_Athletes برای دو سطر برابر باشد، آن‌ها را بر اساس ستون Year به شکل نزولی مرتب کنید.
<br>
در انتها این مجموعه‌داده را با نام زیر در کنار نوت بوک ذخیره کنید:
<br>
athletes_per_year.csv

<br>
در این مرحله، مجموعه‌داده نهایی را با رعایت 2 شرط اساسی ذخیره خواهیم کرد: عدم استفاده از هیچ ستونی به عنوان شاخص ، حفظ صرفاً دو ستون تعیین‌شده (بدون هیچ ستون اضافی). این رویکرد تضمین می‌کند که خروجی نهایی دقیقاً مطابق با الزامات تحلیل بوده و از یکپارچگی داده‌ها اطمینان حاصل می‌شود.

</font>
</p>

In [70]:
df5 = df.groupby('Year').size().reset_index(name='Number_of_Athletes')
df5=df5.sort_values(by=['Number_of_Athletes', 'Year'], ascending=[False, False])
df5.to_csv('athletes_per_year.csv',index=False)
df5

    Year  Number_of_Athletes
26  2000               13682
21  1988               13636
34  2016               13443
30  2008               13402
28  2004               13399
22  1992               13109
32  2012               12524
24  1996               11838
17  1972               11482
20  1984               10868
16  1968               10203
18  1976                9567
15  1964                8711
19  1980                8217
14  1960                8038
33  2014                4673
31  2010                4378
29  2006                4365
27  2002                4060
25  1998                3518
23  1994                2971
13  1956                2595
12  1952                2058
11  1948                1016
10  1936                 896
8   1928                 665
7   1924                 581
5   1912                 551
9   1932                 482
6   1920                 428
4   1908                 364
3   1906                 201
2   1904                 119
1   1900                  71
0   1896                  40

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرحله پایانی: سلول جواب‌ساز
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
بدون هیچگونه تغییری، این سلول را اجرا کنید تا فایل پاسخ شما آماده شود.
</font>
</p>

In [72]:
import zipfile

def compress(file_names):
    print("File Paths:")
    print(file_names)
    # Select the compression mode ZIP_DEFLATED for compression
    # or zipfile.ZIP_STORED to just store the file
    compression = zipfile.ZIP_DEFLATED
    # create the zip file first parameter path/name, second mode
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            # Add file to the zip file
            # first parameter file to zip, second filename in zip
            zf.write('./' + file_name, file_name, compress_type=compression)


file_names = ["notebook.ipynb", "athletes_per_year.csv", "average_stats_by_sport.csv", "event_counts.csv", "gender_distribution.csv", "participants_by_country.csv"]
compress(file_names)

File Paths:
['notebook.ipynb', 'athletes_per_year.csv', 'average_stats_by_sport.csv', 'event_counts.csv', 'gender_distribution.csv', 'participants_by_country.csv']